spring.application.name=To-Do

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=vaibhavnarode56@gmail.com
spring.mail.password=mpbw puow idkw vqjd
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.transport.protocol=smtp

spring.profile.active = {$ENV:dev}

server.servlet.session.timeout=10s



